### ISSUE TITLE
Hooks are ran twice and cannot be CTRL+C

### ISSUE THREAD

**Issue by iCarossio** [Escape-Technologies/mookme#119]
Hey @LMaxence ,

Amazing tool :) Since the last update however hooks are systematically ran twice, plus they cannot be CTRL+C ;)

**Comment by nohehf** [comment]
So for the mookme running twice error, you just have to reset your hooks.
Assuming you only have mookme hooks:
```
rm -rf .git/hooks/
yarn mookme init <params>
```
