### ISSUE TITLE
[Mookme CLI] Testing the CLI

### ISSUE THREAD

**Issue by LMaxence** [Escape-Technologies/mookme#28]
I have in mind to launch official, non-beta releases of the CLI in a near future. This means that we'll use semver and semantic-release to move on with this. The critical issue we need to address is that the CLI should be tested at least for some critical parts.

Since a lot of the results expected by the CLI rely on console display, rather than logical results, and since we do rely a lot on spawning external processes such as every git commands, I feel a bit short-sighted to deal with this part. I'll gladly use any advice on producing reliable and useful tests for such a piece of code.

The critical parts I mentioned above include: 
- `display/logger.ts` -> Remove logging in test environment
- `utils/load-hooks.ts` -> Test interpolations, onlyOn feature
- `utils/hook-package.ts` -> Error processing and generations
- `utils/run-step.ts` -> Make sure the correct command is ran and it's result is correctly interpreted
- `commands/init` -> This could be tested as part of an e2e test with cypress or something like that (or just a script)

There is a lot of config parsing and loading, and I don't really know yet how to handle this part so far. I would avoid having too much `if(process.env.NODE_ENV !== 'test')` in the code ideally.

**Comment by LMaxence** [comment]
here are the critical scenarios involved in configuration management:

-  mookme init
- mookme run + legacy package.json file
- mookme run + .mookme.json file
- mookme run + no configuration -> error

**Comment by MatthewScholefield** [comment]
Imo it's best to just test the "business" logic rather than getting too fine grained. For mookme I think the "business logic" is basically related to whether or not a commit can be committed. So I'd imagine a test would be something like this:

```bash
set -ex
folder=$(mktemp -d)
cd "$folder"
git init
mookme init
git add .
git commit -m "Mookme init and default hooks work"
echo '{"steps": [{"name": "Should Fail", "command": false}]}' > .hooks/pre-commit.json
git add .
! git commit -m "Commit fails if pre-commit hook fails"
echo '{"steps": [{"name": "Custom Command", "command": "get-dir-name"}]}' > .hooks/pre-commit.json
git add .
! git commit -m "Non-existent partial causes hook failure"
{
  echo '#!/usr/bin/env bash'
  echo 'basename "$(pwd)"'
} > .hooks/partials/get-dir-name
chmod +x .hooks/partials/get-dir-name
git add .
git commit -m "Partial commands work correctly"
mookme add-pkg -p "foo-pkg"
[ -f "foo-pkg" ]
echo '{"steps": [{"name": "Check folder", "command": "[  $(get-dir-name) = 'foo-pkg' ]"}]}' > foo-pkg/.hooks/pre-commit.json
git add .
git commit -m "Project hooks run inside project folder"
```

And then it could be extended to include things like `"onlyOn"` and shared hooks.

**Comment by LMaxence** [comment]
We can definitely leverage shell scripts for e2e testing purposes ! I like the `mktemp` idea here. A few things to bear in mind as we move forward in this direction : 

- `mookme init` cannot function without manual inputs, and maybe we'll want to ignore this step for a pre-defined `.mookme.json` file
- A lot of pure js parts of the "business" logic can be unit tested using some more traditional tool like Jest or Mocha.

As I see this, we'll have something like : 

- Everything relying nor on the config, nor on the git helpers can be unit tested using pure js. Let's keep the UI testing out of this scope for now, as I don't know how to test it in any way other than by leveraging manual QA
- Everything depending only on the config is unit tested using js, and config loaders are mocked. I'll work on some code achieving this on Friday.
- Everything relying on git has to be e2e tested (using shell scripts I guess)

Testing a TypeScript library using shell scripts is **way** out of traditional conventions, nonetheless it seems justified here by the Git-based features. We will just have to be very careful about the way it is implemented ;)

**Comment by LMaxence** [comment]
Time is flying by and I'm lacking it to move on with this, I have a basis for generating a temporary scaffold, and running a few mookme commands in them, but I'll need more time to provide a complete and efficient structure

**Comment by MatthewScholefield** [comment]
Btw, just to share my thoughts on the original shell script suggestion, my philosophy is to get the most test coverage with the least effort writing and maintaining tests. This is why I actually don't see a strong need for anything other than either a direct shell script test or a comparable thing done by calling the cli handlers directly in javascript.

In general, if we were dealing with a much more complicated system that was expensive to interact with I think it might make sense, but in my eyes this is a relatively simple system and any failures in the end to end tests should be easily debugged through traditional means (ie. not much savings in fine grained unit tests narrowing the scope of the failure).

Anyways, just wanted to throw that out there.

**Comment by LMaxence** [comment]
Thanks for your help, I followed your guidelines to come up fast with this !
