### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by QuentinN42** [Escape-Technologies/mookme#80]
There is no LICENCE file ...

**Comment by LMaxence** [comment]
Wait what

**Comment by LMaxence** [comment]
Yes there is one ! It is in the `mookme` package, it is the one I use to publish the CLI package. Should I also provide licenses in other package/in the repository root ?

**Comment by QuentinN42** [comment]
Yes, it must be at the repo root to be detected by github [[1]](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) [[2]](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

For example my new repo is ok : [Escape-Technologies/gitlab-auto-labels](https://github.com/Escape-Technologies/gitlab-auto-labels)
![image](https://user-images.githubusercontent.com/32516498/163336972-a6402b4a-039c-44ee-80fb-d973368d6b6a.png)
But not mookme :
![image](https://user-images.githubusercontent.com/32516498/163337024-e336a141-2f14-4487-aa2d-7f439d0159ba.png)

**Comment by LMaxence** [comment]
Fixed it, thanks for pointing it out :)
