### ISSUE TITLE
chmod issue on Windows

### ISSUE THREAD

**Issue by andrewalderson** [Escape-Technologies/mookme#83]
This library attempts to set executable permissions on the hook files by running ```execSync(`chmod +x ${gitFolderPath}/hooks/${type}`)``` in the ```utils/git.ts writeGitHooksFiles```. This produces an error because ```chmod``` doesn't exist on windows.

This can be fixed by removing these lines and passing the mode in the options of the ```fs.appendFileSync``` calls. Basically, changing the method code to:
```
  writeGitHooksFiles(hookTypes: HookType[]): void {
    const gitFolderPath = `${this.rootDir}/.git`;
    if (!fs.existsSync(`${gitFolderPath}/hooks`)) {
      fs.mkdirSync(`${gitFolderPath}/hooks`);
    }

    logger.info('Writing Git hooks files');

    hookTypes.forEach((type) => {
      logger.info(`- ${gitFolderPath}/hooks/${type}`);
      const mookmeCmd = `npx mookme run --type ${type} --args "$1"`;
      if (fs.existsSync(`${gitFolderPath}/hooks/${type}`)) {
        const hook = fs.readFileSync(`${gitFolderPath}/hooks/${type}`).toString();
        if (!hook.includes(mookmeCmd)) {
          fs.appendFileSync(`${gitFolderPath}/hooks/${type}`, `\n${mookmeCmd}`, { flag: 'a+', mode: 0o0755 });  <----  pass mode here
        } else {
          logger.log(`Hook ${type} is already declared, skipping...`);
        }
      } else {
        logger.warning(`Hook ${type} does not exist, creating file...`);
        fs.appendFileSync(`${gitFolderPath}/hooks/${type}`, `#!/bin/bash\n${mookmeCmd}`, { flag: 'a+', mode: 0o0755 }); <---- pass mode here
      }
    });
  }
```

I have already done this work in testing this and can submit a PR if you would like.

**Comment by LMaxence** [comment]
Hello ! Many thanks for giving Mookme a try :)

Your feedback as a Windows user are really precious to me because I did not get the chance to test it on this OS. I should definitely take a deeper look at everything running from an `execSync` for Windows statement but your fix is a very good start.

Please open a pull request and I will look at it in the weekend !

**Comment by andrewalderson** [comment]
Thanks for creating this project. I was looking for the exact solution that this solves.

I was having some issues though with trying to commit this fix. When I committed the changes, the hooks just kept running for some reason. I had to bypass them to commit the changes. I am not sure what was causing this and whether or not if it is Windows related but it shouldn't be. I will wait for the pr to be merged and try the npm package in my repo.

**Comment by andrewalderson** [comment]
Interesting, I reinstalled mookme in my project using the local version I updated and everything works fine. The infinite loop doesn't happen. I did make one change though, in the commit-msg.json step I changed the ```cat {args} | ./node_modules/@commitlint/cli/cli.js``` to use npx ```npx commitlint --edit```. The original command should work on Windows because as far as I know it is run with Git Bash. It seemed to be having a problem with the args that were passed.

**Comment by LMaxence** [comment]
Isn't it because the `commitlint` command does not work on Windows ? I do use that hook at works as well as on other personal projects and I never encountered such an issue on multiple platforms

**Comment by LMaxence** [comment]
Mookme displays the exact command being invoked in the hook, would you please show it to me ? What I need is a screen like this of your UI when the hook runs forever:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/29194680/168464412-fc60ca6b-8d01-4b99-b210-7901b2b2aa58.png">

**Comment by andrewalderson** [comment]
I had an issue with one library related to ```commitlint``` that doesn't work on Windows but ```npx commitlint``` works. At least I haven't had any issues with it.

**Comment by andrewalderson** [comment]
The issue with the hook running forever is not an issue. I am pretty sure it was caused by the linting of all the files failing because of the line endings issue which was solved by adding the ```.gitattributes``` file. It was just taking so long to run that I got impatient and exited the command.
