### ISSUE TITLE
'rm' doesn't exist on Windows

### ISSUE THREAD

**Issue by andrewalderson** [Escape-Technologies/mookme#84]
When working on a fix for #83 I was getting an error with the ```npm prebuild``` script because the ```rm``` utility doesn't exist on Windows. There is a cross platform package (rimraf) that can be used if you want people using Windows to submit PRs. 

Solution:

```npm i -D rimraf``` and change the npm prebuild script to ```"prebuild": "rimraf -f ./.tmp/ts-build-infos.json && rimraf -rf dist"```

**Comment by LMaxence** [comment]
I actually do want that :) You can add that dependency as a dev dependency

**Comment by LMaxence** [comment]
Sorry for closing this, missclick from me
