### ISSUE TITLE
Consider changing the name of the '.hooks' directory

### ISSUE THREAD

**Issue by andrewalderson** [Escape-Technologies/mookme#86]
I was wondering why you decided to name the Mookme hooks directory '.hooks' instead of '.mookme'. Naming directories after the project seems to be a convention used by a lot of other projects (like husky). Also, the config file is called ```.mookme.json```. Naming the directory after the project makes it a lot more explicit as to what it contains. I am not sure at this point how much of an impact a change like this would have. Perhaps an entry could be added to the ```.mookme.json``` file that specifies the directory name.

**Comment by LMaxence** [comment]
Hello ! The fact that the directory is named `.hooks` is just something I decided when implementing Mookme in the first place :). I obviously don't have strong opinions on this, except that it would be a huge breaking change to rename it.

So, if I agree with your suggestion, I will simply schedule it for a v3 release in the futur. Regarding the configurable hooks folder name, I would go for convention over configuration here, and thus do not leave an option for the user to configure it. Whatever we decide it is named, Mookme will be simpler if we decide it is named the same for everyone

**Comment by LMaxence** [comment]
I am truly sorry, but I'm closing this issue, as it requires more attention that I could give it in the last months. Feel free to re-open it with a proposal for implementation. The only criteria would basically be, no breaking change without backward compatibility !
