### ISSUE TITLE
Mookme erasing previous lines in terminal

### ISSUE THREAD

**Issue by fabzo** [Escape-Technologies/mookme#94]
I'm currently experimenting with Mookme in a monorepository on MacOS (12.3.1). I noticed that Mookme will remove lines from my terminal when running my commit-msg hook. 

I'm using Mookme in version 2.1.1 and tested it with iTerm2 as well as the Terminal app. For the shell I'm using zsh with the powerlevel10k theme. Though I also tested it using bash with the same result.

Steps I used to reproduce the issue:
- Init new git repository
- npx mookme init (enable commit-msg hook)
- created a subdirectory with a .hooks folder, a commit-msg.json and script

Directory:
```
❯ tree . -a
.
├── .gitignore
├── .hooks
│   ├── partials
│   │   └── .gitkeep
│   ├── pre-commit.json
│   └── shared
│       └── .gitkeep
├── .mookme.json
└── subdirectory
    ├── .hooks
    │   ├── commit-msg.json
    │   └── fail.sh
    └── testfile

5 directories, 8 files
```

commit-msg.json:
```
{
  "steps": [{
    "name": "Always fails",
    "command": ".hooks/fail.sh"
  }]
}
```

fail.sh:
```
#!/usr/bin/env bash
echo "always fails"
exit 1
```

When adding the file at `subdiretory/testfile` and running a git commit Mookme will output the hook status (which is set up to fail). Unfortunately it will remove some of the previous lines in the terminal as well.

I ran a `seq 100` to before running git commit to get a sense of what is missing. The `seq 100` will output all numbers from 1 to 100. After running git commit the terminal looks as follows:

```
{Prompt} /tmp/test_repository
❯ seq 100
1
2
3
4
5
6
7
8
9
10
11
12
13
  0 test
14

 Hooks : subdirectory  Error ×
→ Always fails > .hooks/fail.sh
❌ Error.

Hook of package subdirectory failed at step Always fails

stdout :

always fails


{Prompt} /tmp/test_repository 
❯
```

The `test` on line 16 here is the commit message.

What am I doing wrong? Is this a bug or simply a misconfiguration on my side? Also, is there a fallback mode that just prints the hook status line by line?

Please let me know if this might be a bug and I might be able to help debugging it in some way.

**Comment by LMaxence** [comment]
What I might have in mind to get rid of the fancy, yet hard to bear UI, is an output like this:

```
packageA:stepA:created
packageA:stepB:created
packageA:stepA:running
packageA:stepA:success
packageA:stepB:running
packageA:stepB:failed

[Failure output]
```

What do you think of it ?

**Comment by fabzo** [comment]
An alternative display mode (as you suggested) would probably be interesting if it could be configured via the config file for cases where it's more desirable.

I assume there isn't really a good alternative way of displaying the information due to the parallel execution happening in most cases right? Delaying the output just to have it properly serialized might also most likely not be desirable.

Personally I would still feel better with such a simpler line by line printed output. Instead of erasing too much of a users terminal.

A third alternative might be to force everything to run serialized regardless of the configuration. While that would be a hit on the runtime it would allow for a nicer output. But that might be a separate feature?

**Comment by LMaxence** [comment]
You can already run them in serial mode :) Yet, one of the major interest of mookme is to parallelize git hooks execution.

Generally speaking, if running your git hooks are too slow, where too slow means whatever your team can agree on, your hooks are simply bypassed and there is no point in using Mookme anymore.

It would be a massive setback to remove this feature for the sake of clean logs.

On the other side, the failure outputs are displayed only at the end of all execution, so we could indeed have a mode where we do this:

```
packageA:stepA:created
packageA:stepB:created
packageA:stepA:running
packageA:stepA:success
packageA:stepB:running
packageA:stepB:failed
```

without compromising the global UI

**Comment by LMaxence** [comment]
We can make an option in the mookme config file to ask for a `noclear` output mode the would follow the design above. It would not be the default one, but it leaves you with the ability to ask Mookme no to clear your console

**Comment by fabzo** [comment]
I like the idea. It would alleviate the current issues with the `clear` based output for those who are interested and provide something to iterate over later on.
