### ISSUE TITLE
Logs have been truncated due to a small output area

### ISSUE THREAD

**Issue by alexsavio** [Escape-Technologies/mookme#97]
Hi,

I have tried using mookme, it is really nice, and it works well when I launch it from my prompt. However when git runs it, I get this message: `Logs have been truncated due to a small output area` and, in addition, it does not fail when it is supposed to.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2472076/179343429-3dbbfdee-8275-41e4-84d1-d88c380b452c.png">

It might be an issue with my terminal configuration, but maybe you know what might be the reason?
I am using iTerm2, ZSH, Starship...

Thank you!

**Comment by LMaxence** [comment]
Hello ! Thanks for reporting this :)

From my point of view it is hard to tell why Mookme does not work properly on your very setup. Would you mind setting up a small repository where the problem can be reproduced please ?

The `Logs have been...` output is displayed when the console is indeed too long for the console (computed with `process.stdout.rows`)

Finally, what do you mean by `it does not fail when it is supposed to` ? For mookme to fail, the executed command needs to return an exit code above 0 (just not 0 more precisely).

**Comment by alexsavio** [comment]
Hi! Thanks for the reply.

I tried running mookme in plain bash as well in my computer in 2 ways: directly calling mookme and through the `git commit` hook. I got the same result through bash: the former works fine, but when git launches the hook I get the same list of `Logs have been...` lines but now without color.

When I say `it does not fail when it is supposed to` I mean that when I run mookme through the CLI for a code scenario where it should report an error, it does report the error. On the other hand, if I run against the same staged files with errors the commit hook run shows those `Logs have been...` lines, but in the end it does not report the error that it should have reported and the commit is done.

I am a pre-commit user, and I tried to migrate to mookme exactly because I am trying to configure it for a monorepo and I ended up doing ugly hacks that are unexplainable and hard to maintain. I don't know much about how git handles the process of the hooks, but I know that it handles it because my prompt is different when I run `pre-commit run --all` and when it is triggered through the git hook. So I thought that the issue would be because of some git configuration.

I will create a sample repo and share it here soon.

**Comment by alexsavio** [comment]
No, sorry, my memory failed. So, after I do a `git commit` and I get those `Logs have been...` messages, git behaves as expected: the commit is done if there is no errors, it exits otherwise.

**Comment by alexsavio** [comment]
I also tried only with the hello world hook that mookme creates, but I am still getting the same issue.

**Comment by alexsavio** [comment]
I also got the same result in the native MacOS terminal application in zsh and bash.

**Comment by alexsavio** [comment]
The culprit was a step in my zsh setup running `brew shellenv`. I removed it and now mookme works.
It's fast and the setup is clean. It's great. Thank you!

**Comment by LMaxence** [comment]
I'm glad you could figure it out ! Feel free to re-open if something goes wrong :)
